### ISSUE TITLE
View My Events Page: Create API endpoint that requests all events created by a specific user (by user ID)

### ISSUE THREAD

**Issue by bennettsf** [SeattleColleges/nsc-events-nestjs#106]
Related: https://github.com/SeattleColleges/nsc-events-nextjs/issues/251

getActivitiesByUserId API endpoint

I would like to create an API endpoint that will access a specific user's created events from the database. This will be helpful for the related issue above, as it will allow us to display events on the 'View My Events' page that were created by the currently logged-in user.

**Comment by bennettsf** [comment]
For testing (this assumes you have your database setup already):

1. Change to the development branch **feature-106-user-events-API-endpoint-01**. 
2. Start the backend nsc-events-nestjs server! `npm run start:dev`
3. After creating a few events (through API calls or on the local nextjs server), go to your MongoDB compass and grab the User ID from any of the Events you created. The User ID is found in the `createdByUser` property.
4. Paste that User ID in the Postman app as a GET request. (Append it to the end of `http://localhost:3000/api/events/user/`
5. If you have any trouble setting this up, don't hesitate to reach out to me!

https://github.com/SeattleColleges/nsc-events-nestjs/assets/33855430/9831b367-ce00-4cf5-a5bb-e494ec39f806

**Comment by taylorpapke** [comment]
I went ahead and consolidated #105 into this issue since it is under the umbrella of user story https://github.com/SeattleColleges/nsc-events-nextjs/issues/251

Backend issues can go under a frontend user story as long as it is references it. A backend user story should only be created if there is no frontend user story.
