### ISSUE TITLE
USER STORY (Backend): Unit tests for User controller and services module

### ISSUE THREAD

**Issue by Robel-003** [SeattleColleges/nsc-events-nestjs#38]
**Task**: User controller and services module need unit testing

**Solution**: I want to create unit tests for the user controller and user service modules

**_Specific issues_**:		

- [x] Create unit test for the user controller module
 
- [x] Create unit test for the user service module

_Resources_:
- https://docs.nestjs.com/fundamentals/testing
- https://www.youtube.com/watch?v=lih9VT0IZ7U&t=1163s,
- https://www.youtube.com/watch?v=dxTuOkgSKh4

**Comment by CourtneyHoppus** [comment]
I have started implementing testing for the service and controller like Belinda's [product](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/44) and [user](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/48) testing.
I will open an issue to create a DTO for updating a User and to refactor the service and controller, similar to what I did for Belinda's [controller](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/53) and [DTOs](https://github.com/SeattleColleges/belindas-closet-nestjs/pull/51)
